networks:
  cosmic_network:
    name: cosmic_network

services:
  traefik:
    image: traefik:${TRAEFIK_IMAGE_VERSION}
    command:
      - --api.dashboard=${TRAEFIK_ENABLE_DASHBOARD}
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=cosmic_network

      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443

      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.http.http.redirections.entrypoint.permanent=true

      - --entrypoints.https.http.tls=true
      - --entrypoints.https.http.tls.certresolver=letsencrypt

      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
    restart: unless-stopped
    networks: [cosmic_network]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_FULLY_QUALIFIED_DOMAIN_NAME}`)
      - traefik.http.routers.traefik.service=api@internal
      # strongly recommended for consistency:
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt

  cosmic_latte:
    image: eclipse-temurin:21-jre
    working_dir: /app
    volumes:
      - ./target/DAI-Practical-work-3-1.0-SNAPSHOT.jar:/app/app.jar:ro
    command: ["java", "-jar", "/app/app.jar"]
    restart: unless-stopped
    networks: [cosmic_network]
    labels:
      - traefik.enable=true
      - traefik.http.routers.cosmic.entrypoints=https
      - traefik.http.routers.cosmic.rule=Host(`${COSMIC_FULLY_QUALIFIED_DOMAIN_NAME}`)
      - traefik.http.routers.cosmic.tls=true
      - traefik.http.routers.cosmic.tls.certresolver=letsencrypt
      - traefik.http.services.cosmic.loadbalancer.server.port=8080
